// jela-website/src/lib/heroImages.ts
//
// GENERATED by scripts/gen-hero-images.mjs - do not edit by hand.
// Source: /hero/ (41 images available)

export type HeroImage = { src: string; width: number; height: number }

export const heroColumns: HeroImage[][] = [
  [
    { src: '/hero/3.jpg', width: 635, height: 1848 },
    { src: '/hero/14.jpg', width: 1378, height: 996 },
    { src: '/hero/13.jpg', width: 457, height: 1357 },
    { src: '/hero/20.jpg', width: 479, height: 1443 },
    { src: '/hero/33.jpg', width: 617, height: 859 },
  ],
  [
    { src: '/hero/1.jpg', width: 845, height: 1680 },
    { src: '/hero/9.jpg', width: 493, height: 1213 },
    { src: '/hero/23.jpg', width: 819, height: 858 },
    { src: '/hero/27.jpg', width: 867, height: 1140 },
    { src: '/hero/35.jpg', width: 333, height: 949 },
  ],
  [
    { src: '/hero/5.jpg', width: 634, height: 1841 },
    { src: '/hero/18.jpg', width: 1122, height: 1044 },
    { src: '/hero/15.jpg', width: 308, height: 689 },
    { src: '/hero/24.jpg', width: 229, height: 930 },
    { src: '/hero/34.jpg', width: 478, height: 790 },
  ],
  [
    { src: '/hero/2.jpg', width: 875, height: 1386 },
    { src: '/hero/10.jpg', width: 718, height: 1560 },
    { src: '/hero/16.jpg', width: 583, height: 1545 },
    { src: '/hero/28.jpg', width: 692, height: 1057 },
    { src: '/hero/36.jpg', width: 469, height: 1080 },
  ],
  [
    { src: '/hero/6.jpg', width: 554, height: 1310 },
    { src: '/hero/11.jpg', width: 459, height: 976 },
    { src: '/hero/25.jpg', width: 764, height: 1194 },
    { src: '/hero/29.jpg', width: 575, height: 1220 },
    { src: '/hero/38.jpg', width: 461, height: 1446 },
  ],
  [
    { src: '/hero/4.jpg', width: 950, height: 1100 },
    { src: '/hero/21.jpg', width: 827, height: 632 },
    { src: '/hero/17.jpg', width: 414, height: 975 },
    { src: '/hero/32.jpg', width: 978, height: 1752 },
    { src: '/hero/37.jpg', width: 1219, height: 2173 },
  ],
  [
    { src: '/hero/7.jpg', width: 884, height: 2093 },
    { src: '/hero/12.jpg', width: 481, height: 1139 },
    { src: '/hero/26.jpg', width: 1418, height: 2163 },
    { src: '/hero/30.jpg', width: 900, height: 2243 },
    { src: '/hero/39.jpg', width: 1000, height: 2049 },
  ],
  [
    { src: '/hero/8.jpg', width: 649, height: 1895 },
    { src: '/hero/22.jpg', width: 432, height: 695 },
    { src: '/hero/19.jpg', width: 554, height: 1289 },
    { src: '/hero/31.jpg', width: 637, height: 1546 },
    { src: '/hero/41.jpg', width: 1523, height: 981 },
  ],
]
